/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.ferstock.sys.ferstock;

import java.awt.CardLayout;
import java.awt.Color;
import java.awt.Cursor;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.GridLayout;
import java.awt.Insets;
import java.awt.Rectangle;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.beans.Beans;
import java.io.IOException;
import javax.swing.BorderFactory;
import javax.swing.BoxLayout;
import javax.swing.GroupLayout;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.LayoutStyle;
import javax.swing.SwingConstants;
import javax.swing.WindowConstants;

/**
 *
 * @author lucas
 */
public class MainScreen extends javax.swing.JFrame {

    /**
     * Creates new form MainScreen
     */
    public MainScreen() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelSideMenu = new JPanel();
        btnSideHome = new JButton();
        btnSideAdd = new JButton();
        btnSideRemove = new JButton();
        btnSideConfig = new JButton();
        panelMainContent = new JPanel();
        topDisplay = new JPanel();
        labelTitle = new JLabel();
        labelBalance = new JLabel();
        panelHome = new JPanel();
        panelScreenMenus = new JPanel();
        btnMovimentacao = new JButton();
        btnRelatorio = new JButton();
        btnConfig = new JButton();

        setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Ferstock - Financeiro");
        setBackground(new Color(0, 12, 26));
        setBounds(new Rectangle(0, 0, 0, 0));
        setMaximumSize(new Dimension(3000, 3000));
        setMinimumSize(new Dimension(1280, 720));
        setName("MainFrame"); // NOI18N
        setPreferredSize(new Dimension(1280, 720));
        setSize(new Dimension(1280, 720));
        getContentPane().setLayout(new BoxLayout(getContentPane(), BoxLayout.LINE_AXIS));

        panelSideMenu.setBackground(new Color(214, 128, 0));
        panelSideMenu.setBorder(BorderFactory.createEmptyBorder(12, 5, 12, 5));
        panelSideMenu.setMaximumSize(new Dimension(80, 2147483647));
        panelSideMenu.setMinimumSize(new Dimension(62, 542));
        panelSideMenu.setPreferredSize(new Dimension(62, 561));
        panelSideMenu.setLayout(new GridLayout(4, 2, 0, 150));

        btnSideHome.setToolTipText("Início");
        btnSideHome.setAlignmentX(0.5F);
        btnSideHome.setBorder(BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnSideHome.setBorderPainted(false);
        btnSideHome.setContentAreaFilled(false);
        btnSideHome.setFocusable(false);
        btnSideHome.setMargin(new Insets(0, 0, 0, 0));
        panelSideMenu.add(btnSideHome);

        btnSideAdd.setToolTipText("Movimentação");
        btnSideAdd.setAlignmentX(0.5F);
        btnSideAdd.setBorderPainted(false);
        btnSideAdd.setContentAreaFilled(false);
        btnSideAdd.setFocusPainted(false);
        btnSideAdd.setFocusable(false);
        btnSideAdd.setHorizontalTextPosition(SwingConstants.CENTER);
        btnSideAdd.setIconTextGap(5);
        btnSideAdd.setMargin(new Insets(0, 0, 0, 0));
        btnSideAdd.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                btnSideAddActionPerformed(evt);
            }
        });
        panelSideMenu.add(btnSideAdd);

        btnSideRemove.setToolTipText("Relatório");
        btnSideRemove.setBorderPainted(false);
        btnSideRemove.setContentAreaFilled(false);
        btnSideRemove.setFocusable(false);
        btnSideRemove.setMargin(new Insets(0, 0, 0, 0));
        btnSideRemove.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                btnSideRemoveActionPerformed(evt);
            }
        });
        panelSideMenu.add(btnSideRemove);

        btnSideConfig.setToolTipText("Configurações");
        btnSideConfig.setBorderPainted(false);
        btnSideConfig.setContentAreaFilled(false);
        btnSideConfig.setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
        btnSideConfig.setFocusable(false);
        btnSideConfig.setMargin(new Insets(0, 0, 0, 0));
        btnSideConfig.setMaximumSize(new Dimension(32, 32));
        btnSideConfig.setMinimumSize(new Dimension(32, 32));
        btnSideConfig.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                btnSideConfigActionPerformed(evt);
            }
        });
        panelSideMenu.add(btnSideConfig);

        getContentPane().add(panelSideMenu);

        panelMainContent.setLayout(new BoxLayout(panelMainContent, BoxLayout.PAGE_AXIS));

        topDisplay.setBackground(new Color(45, 47, 48));
        topDisplay.setMaximumSize(new Dimension(32767, 55));
        topDisplay.setMinimumSize(new Dimension(0, 55));
        topDisplay.setPreferredSize(new Dimension(1126, 55));

        labelTitle.setFont(new Font("Segoe UI", 1, 18)); // NOI18N
        labelTitle.setForeground(new Color(255, 255, 255));
        labelTitle.setText("Ferstock - Gerenciamento de Caixa");

        labelBalance.setFont(new Font("Gadugi", 1, 28)); // NOI18N
        labelBalance.setForeground(new Color(10, 129, 10));
        labelBalance.setHorizontalAlignment(SwingConstants.RIGHT);
        labelBalance.setText("957,62");
        labelBalance.setToolTipText("Saldo atual");
        labelBalance.setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
        labelBalance.setHorizontalTextPosition(SwingConstants.RIGHT);
        labelBalance.setIconTextGap(15);

        GroupLayout topDisplayLayout = new GroupLayout(topDisplay);
        topDisplay.setLayout(topDisplayLayout);
        topDisplayLayout.setHorizontalGroup(topDisplayLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(topDisplayLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelTitle)
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(labelBalance, GroupLayout.PREFERRED_SIZE, 279, GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28))
        );
        topDisplayLayout.setVerticalGroup(topDisplayLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(topDisplayLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(labelTitle, GroupLayout.PREFERRED_SIZE, 17, GroupLayout.PREFERRED_SIZE)
                .addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(GroupLayout.Alignment.TRAILING, topDisplayLayout.createSequentialGroup()
                .addContainerGap(11, Short.MAX_VALUE)
                .addComponent(labelBalance)
                .addContainerGap())
        );

        panelMainContent.add(topDisplay);

        panelHome.setBackground(new Color(58, 60, 62));
        panelHome.setBorder(BorderFactory.createEmptyBorder(1, 1, 1, 1));
        panelHome.setMinimumSize(new Dimension(0, 32));
        panelHome.setPreferredSize(new Dimension(1280, 720));
        panelHome.setLayout(new CardLayout(300, 200));

        panelScreenMenus.setBorder(BorderFactory.createEmptyBorder(50, 50, 50, 50));
        panelScreenMenus.setMaximumSize(new Dimension(800, 600));
        panelScreenMenus.setOpaque(false);
        panelScreenMenus.setPreferredSize(new Dimension(1000, 600));
        panelScreenMenus.setLayout(new GridLayout(1, 3, 20, 0));

        btnMovimentacao.setFont(new Font("Segoe UI", 0, 18)); // NOI18N
        btnMovimentacao.setText("Movimentação");
        btnMovimentacao.setToolTipText("Gerencia a entrada e saída de valores");
        btnMovimentacao.setContentAreaFilled(false);
        btnMovimentacao.setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
        btnMovimentacao.setFocusable(false);
        btnMovimentacao.setHorizontalTextPosition(SwingConstants.CENTER);
        btnMovimentacao.setMaximumSize(new Dimension(45, 45));
        btnMovimentacao.setPreferredSize(new Dimension(45, 45));
        btnMovimentacao.setVerticalTextPosition(SwingConstants.BOTTOM);
        panelScreenMenus.add(btnMovimentacao);

        btnRelatorio.setBackground(new Color(149, 0, 110));
        btnRelatorio.setFont(new Font("Segoe UI", 0, 18)); // NOI18N
        btnRelatorio.setText("Relatório");
        btnRelatorio.setToolTipText("Emite documentos referente à movimentação financeira");
        btnRelatorio.setBorder(BorderFactory.createEmptyBorder(10, 10, 10, 10));
        btnRelatorio.setBorderPainted(false);
        btnRelatorio.setContentAreaFilled(false);
        btnRelatorio.setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
        btnRelatorio.setFocusPainted(false);
        btnRelatorio.setFocusable(false);
        btnRelatorio.setHorizontalTextPosition(SwingConstants.CENTER);
        btnRelatorio.setMargin(new Insets(0, 0, 0, 0));
        btnRelatorio.setMaximumSize(new Dimension(40, 40));
        btnRelatorio.setPreferredSize(new Dimension(40, 40));
        btnRelatorio.setVerticalTextPosition(SwingConstants.BOTTOM);
        btnRelatorio.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                btnRelatorioActionPerformed(evt);
            }
        });
        panelScreenMenus.add(btnRelatorio);

        btnConfig.setFont(new Font("Segoe UI", 0, 18)); // NOI18N
        btnConfig.setText("Configurações");
        btnConfig.setToolTipText("Altera as definições de funcionamento e gerenciamento do programa");
        btnConfig.setContentAreaFilled(false);
        btnConfig.setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
        btnConfig.setFocusable(false);
        btnConfig.setHorizontalTextPosition(SwingConstants.CENTER);
        btnConfig.setMaximumSize(new Dimension(50, 50));
        btnConfig.setMinimumSize(new Dimension(50, 50));
        btnConfig.setVerticalTextPosition(SwingConstants.BOTTOM);
        panelScreenMenus.add(btnConfig);

        panelHome.add(panelScreenMenus, "card2");

        panelMainContent.add(panelHome);

        getContentPane().add(panelMainContent);

        setSize(new Dimension(1296, 728));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnSideAddActionPerformed(ActionEvent evt) {//GEN-FIRST:event_btnSideAddActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSideAddActionPerformed

    private void btnSideRemoveActionPerformed(ActionEvent evt) {//GEN-FIRST:event_btnSideRemoveActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSideRemoveActionPerformed

    private void btnSideConfigActionPerformed(ActionEvent evt) {//GEN-FIRST:event_btnSideConfigActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSideConfigActionPerformed

    private void btnRelatorioActionPerformed(ActionEvent evt) {//GEN-FIRST:event_btnRelatorioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRelatorioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new MainScreen().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    JButton btnConfig;
    JButton btnMovimentacao;
    JButton btnRelatorio;
    JButton btnSideAdd;
    JButton btnSideConfig;
    static JButton btnSideHome;
    JButton btnSideRemove;
    JLabel labelBalance;
    JLabel labelTitle;
    JPanel panelHome;
    JPanel panelMainContent;
    JPanel panelScreenMenus;
    JPanel panelSideMenu;
    JPanel topDisplay;
    // End of variables declaration//GEN-END:variables
}

